# Generated by Django 3.2.13 on 2022-04-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personas_covid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fuerzas', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'EA'), (2, 'FAA'), (3, 'ARA')])),
                ('activos', models.IntegerField(blank=True, default=0, null=True)),
                ('recuperados', models.IntegerField(blank=True, default=0, null=True)),
                ('sospechosos', models.IntegerField(blank=True, default=0, null=True)),
                ('fallecidos', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
