# Generated by Django 3.2.13 on 2022-04-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSituacionCovid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='camas_hospitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cama', models.DateField()),
                ('camas_ocupadas', models.IntegerField(blank=True, default=0, null=True)),
                ('camas_libres', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='hospitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=50)),
                ('region', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'AMBA'), (2, 'INTERIOR')])),
            ],
        ),
        migrations.RenameField(
            model_name='personas_covid',
            old_name='fecha',
            new_name='fecha_personas',
        ),
    ]
