# Generated by Django 3.2.13 on 2022-04-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSituacionCovid', '0002_auto_20220426_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personas_covid',
            old_name='fuerzas',
            new_name='fuerza',
        ),
    ]
