# Generated by Django 3.2.13 on 2022-04-26 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appSituacionCovid', '0003_rename_fuerzas_personas_covid_fuerza'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitales',
            name='fuerza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appSituacionCovid.personas_covid'),
        ),
    ]
