# Generated by Django 3.2.13 on 2022-04-26 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appSituacionCovid', '0004_hospitales_fuerza'),
    ]

    operations = [
        migrations.AddField(
            model_name='camas_hospitales',
            name='fuerza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appSituacionCovid.hospitales'),
        ),
        migrations.AlterField(
            model_name='hospitales',
            name='fuerza',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'EA'), (2, 'FAA'), (3, 'ARA')]),
        ),
    ]
