# Generated by Django 3.2.13 on 2022-04-26 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSituacionCovid', '0005_auto_20220426_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camas_hospitales',
            old_name='fuerza',
            new_name='hospital',
        ),
    ]
