# Generated by Django 3.2.13 on 2022-04-27 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSituacionCovid', '0006_rename_fuerza_camas_hospitales_hospital'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camas_hospitales',
            options={'verbose_name_plural': 'Camas Hospitales'},
        ),
        migrations.AlterModelOptions(
            name='hospitales',
            options={'verbose_name_plural': 'Hospitales'},
        ),
        migrations.AlterModelOptions(
            name='personas_covid',
            options={'verbose_name_plural': 'Situación Sanitaria - Personal Militar Actividad '},
        ),
    ]
