# Generated by Django 3.2.13 on 2022-04-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSituacionCovid', '0007_auto_20220427_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='camas_hospitales',
            name='situacion',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'CRITICAS'), (2, 'INTERMEDIAS'), (3, 'AISLAMIENTO')], null=True),
        ),
    ]
