# Generated by Django 3.2.13 on 2022-04-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSituacionCovid', '0008_camas_hospitales_situacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitales',
            name='fuerza',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'EA'), (2, 'FAA'), (3, 'ARA')], null=True),
        ),
        migrations.AlterField(
            model_name='hospitales',
            name='region',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'AMBA'), (2, 'INTERIOR')], null=True),
        ),
        migrations.AlterField(
            model_name='personas_covid',
            name='fuerza',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'EA'), (2, 'FAA'), (3, 'ARA')], null=True),
        ),
    ]
