# Generated by Django 3.2.13 on 2022-05-02 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSituacionCovid', '0009_auto_20220429_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personas_covid',
            name='fecha_personas',
        ),
    ]
