# Generated by Django 3.2.13 on 2022-05-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSituacionCovid', '0011_auto_20220502_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camas_hospitales',
            name='Semana_camas',
        ),
        migrations.AddField(
            model_name='camas_hospitales',
            name='semana_camas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='personas_covid',
            name='semana_persmil',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
