# Generated by Django 3.2.13 on 2022-05-02 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSituacionCovid', '0012_auto_20220502_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camas_hospitales',
            old_name='semana_camas',
            new_name='semana',
        ),
        migrations.RenameField(
            model_name='personas_covid',
            old_name='semana_persmil',
            new_name='semana',
        ),
    ]
