# Generated by Django 3.2.13 on 2022-05-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSituacionCovid', '0013_auto_20220502_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas_covid',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
