# Generated by Django 3.2.13 on 2022-05-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSituacionCovid', '0014_personas_covid_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitales',
            name='total_de_camas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
