# Generated by Django 3.2.13 on 2022-05-06 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSituacionCovid', '0016_auto_20220506_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camas_hospitales',
            old_name='camas_ocupadas',
            new_name='semana',
        ),
        migrations.RemoveField(
            model_name='hospitales',
            name='semana',
        ),
    ]
